### ISSUE TITLE
Templates: http-csharp custom filters not supported in Spin 2.0

### ISSUE THREAD

**Issue by vdice** [fermyon/spin-dotnet-sdk#53]
The [http-csharp template](https://github.com/fermyon/spin-dotnet-sdk/tree/main/templates/http-csharp) employs custom filters which are no longer supported in the forthcoming Spin 2.0 (ref https://github.com/fermyon/spin/pull/1822).

Is there another way to use the dotted-pascal-case-filter in `tools` for formatting?

**Comment by mikkelhegn** [comment]
Fixed in #55

**Comment by mikkelhegn** [comment]
I'm not sure if this covers everything related to this issue.

**Comment by vdice** [comment]
Oh nice, I believe https://github.com/fermyon/spin-dotnet-sdk/pull/55 does cover this one.  Will defer to @itowlson to confirm and close.

**Comment by itowlson** [comment]
It does. 
![image](https://github.com/fermyon/spin-dotnet-sdk/assets/865538/ef5d1f24-c5a2-4f47-94d8-d83298427d6d)
